### PR TITLE
Buildable filter search

### PR DESCRIPTION
**Pull request by laurakwhit**
## Description & motivation 💭 
Ads new buildable filter search hidden behind labs flag. Set `labs=true` as a query param on the `Recent Workflows` page to view. 

Allows users to
* See and search all possible search attributes
* Build the query via dropdowns and inputs
* See, edit, and remove all queries 
   * First 5 queries are always shown, additional can be seen with `View more` button 
* Toggle `View Search Input` to manually input query string

**Note:** `KeywordList` search attributes are currently not supported.

### Screenshots (if applicable) 📸 

Screenshot 2023-07-17 at 8 53 15 AM
Screenshot 2023-07-17 at 8 53 29 AM

| Search attributes | Conditional dropdown | Datetime dropdown | ExecutionStatus dropdown | 
|--|--| --| --| 
|Screenshot 2023-07-17 at 8 50 25 AM|Screenshot 2023-07-17 at 8 50 48 AM|Screenshot 2023-07-17 at 9 26 15 AMScreenshot 2023-07-20 at 12 46 28 PM|Screenshot 2023-07-20 at 12 44 59 PM|

### How was this tested 👻 

- [x] Manual testing
- [ ] E2E tests added
- [ ] Unit tests added

### CODE REVIEW

**Comment by Alex-Tideman** [comment]
Okay this is super cool.

Here's a few things I found:
1. We should sort the list of filters by "popularity" (at least a few of them, then the rest alpha sorted. So ExecutionStatus, WorkflowType, WorkflowId, TaskQueue?, ...rest
2. Opening the Status filter to show the multi-select is a little... funky. Has some weird flashes of black.
3. I think we should include the number input with the date unit dropdown for BEFORE/AFTER. To enter like 5 mins or 10 days or whatever.
Screen Shot 2023-07-18 at 3 56 00 PM
4. What are your thoughts on adding quotes in the chip for the text/keyword? TaskQueue = "canary-task-queue"
Screen Shot 2023-07-18 at 3 57 48 PM

**Comment by laurakwhit** [comment]
@Alex-Tideman thanks for the feedback! 
> We should sort the list of filters by "popularity" (at least a few of them, then the rest alpha sorted. So ExecutionStatus, WorkflowType, WorkflowId, TaskQueue?, ...rest

I've sorted them based on these options first (since those were the existing filters), but open to changing them.

> Opening the Status filter to show the multi-select is a little... funky

Looks like that `fade` transition isn't going to work for us there. Removed it for now. Will look into alternatives/fixes.

> I think we should include the number input with the date unit dropdown for BEFORE/AFTER

What do you think of something like this for now?

Screenshot 2023-07-19 at 4 57 51 PM

> What are your thoughts on adding quotes in the chip for the text/keyword?

Added!

**Comment by Alex-Tideman** [comment]
Those all look great! This feature is really a huge improvement, people are going to love it.

The one thing that keeps tripping me up in the date/time picker is relative time. I had do to some thinking on, okay what doing I use for looking in the last 5 minutes? AFTER 5 minutes? BEFORE 5 minutes? Neither of those immediately make sense. I added this to remember (not saying we should), but something to think about. 

Screen Shot 2023-07-19 at 8 41 07 PM

I think we'll want to also preserve times, so when you create a BETWEEN date filter, and you click the clip, the date/time values are set so you can quickly change just the end date or something along those lines. I know that's gonna be tricky, don't need it for this PR.

69a46aeb0c2c30ee

**Comment by Alex-Tideman** [comment]
Yup I went down that road already, but wanted to merge this one in first. We can definitely do that.

**Review by Alex-Tideman — APPROVED** [review]

**Review by rossedfort — APPROVED** [review]

**Pull request merged**
