### PR TITLE
DT-1495 - use description instead of tooltip on reset menu item

### PR DESCRIPTION
**Pull request by rossedfort**
## Description & motivation 💭 
Instead of changing Menu and/or MenuItem to support tooltips, this PR removes the only occurrence of using a Tooltip on a MenuItem (workflow reset) and uses the MenuItem's description prop instead

### Screenshots (if applicable) 📸 
Screenshot 2024-10-08 at 11 26 32 AM
Screenshot 2024-10-08 at 11 27 18 AM

### How was this tested 👻 

- [x] Manual testing
- [ ] E2E tests added
- [ ] Unit tests added

### CODE REVIEW

**Comment by Alex-Tideman** [comment]
What are your thoughts on making the width wider on the menu item? It's a lot of text in a narrow width, makes it hard to read.

**Comment by rossedfort** [comment]
> What are your thoughts on making the width wider on the menu item? It's a lot of text in a narrow width, makes it hard to read.

I agree, although this could be tricky to solve generically. The width of the MenuItem is inherited from the width of the Menu, which is inherited from the width of the trigger element (in this case the split button). We can hardcode a width on this specific menu I suppose, but may be tricky if we want to solve across the board.

**Comment by Alex-Tideman** [comment]
I think it's probably fine to do it just for this Menu and not generically. I do the same on the Event Type Filter because of the long descriptions.

**Comment by rossedfort** [comment]
Part of the problem here is the workflow task names don't have any whitespace, so they don't break.

Screenshot 2024-10-08 at 11 14 06 AM

Breaking on all isn't great either

Screenshot 2024-10-08 at 11 15 47 AM

**Comment by Alex-Tideman** [comment]
I'd probably just make the width wide enough to fit the first full event type. Also should we change the direction to go left?

**Comment by rossedfort** [comment]
> I'd probably just make the width wide enough to fit the first full event type. Also should we change the direction to go left?

@Alex-Tideman Yep, good call, updated screenshot in the PR description

**Review by Alex-Tideman — APPROVED** [review]

**Pull request merged**
