### PR TITLE
UserMenu refactoring

### PR DESCRIPTION
**Pull request by Alex-Tideman**
## Description & motivation 💭 
Pass UserMenu as a slot into the TopNav and BottomNav.

Also make all MenuItems hoverable, add a actionTooltip prop to Combobox, improve styles of bottom nav Namespace switcher.

### Screenshots (if applicable) 📸 
Screenshot 2024-10-08 at 2 36 45 PM
Screenshot 2024-10-08 at 2 36 56 PM
Screenshot 2024-10-08 at 2 39 30 PM
Screenshot 2024-10-08 at 2 39 47 PM
Screenshot 2024-10-09 at 8 51 07 AM
Screenshot 2024-10-09 at 8 54 16 AM

### How was this tested 👻 

- [x] Manual testing
- [ ] E2E tests added
- [ ] Unit tests added

### CODE REVIEW

**Review by rossedfort — APPROVED** [review]
Aside from the tooltip in Combobox lgtm

**Comment by Alex-Tideman** [comment]
Like don't include the actionTooltip prop? When I wrap the Button in the Tooltip and pass it into the slot, it doesn't render. Thus the prop.

**Comment by rossedfort** [comment]
Hah it's OK, I'm just salty on tooltips. But just FYI the tooltip probably won't show on mobile cause no hover, so I'm curious how you go that screenshot

**Comment by Alex-Tideman** [comment]
Yeah I think I'll remove the mobile tooltip

**Pull request merged**
