### PR TITLE
DT-2347 - support multiselect in combobox

### PR DESCRIPTION
**Pull request by rossedfort**
## Description & motivation 💭 
- Add functionality to the `<Combobox />` component to support multiselect

### Screenshots (if applicable) 📸 

https://github.com/user-attachments/assets/7deac79d-68b4-4361-a7ab-94bb97f8cfcb

https://github.com/user-attachments/assets/c56cce77-6cb8-4957-a0e1-b632094db98f

### How was this tested 👻 

- [ ] Manual testing
- [ ] E2E tests added
- [ ] Unit tests added

### CODE REVIEW

**Comment by Alex-Tideman** [comment]
Screenshot 2024-09-26 at 1 58 56 PM

Might want some padding with no leadingIcon

**Comment by Alex-Tideman** [comment]
Screenshot 2024-09-26 at 2 01 42 PM

Probably don't want the placeholder when selected

**Comment by rossedfort** [comment]
> Screenshot 2024-09-26 at 2 01 42 PM
> Probably don't want the placeholder when selected

I think we still do, but maybe the `n options selected` text should go in a badge? I think hiding the placeholder is weird cause then it doesn't really come across as an input you can filter.

Screenshot 2024-09-26 at 2 22 26 PM

**Comment by Alex-Tideman** [comment]
Ohh I like that

**Pull request merged**
