### PR TITLE
Fix is unauthorized

### PR DESCRIPTION
**Pull request by Alex-Tideman**
## What was changed
Check only for statusCode on response for isUnauthorized and isForbidden.

## Why?
The isNetworkError was returning false because some response bodys are undefined:

```
    networkErr?.statusCode !== undefined &&
    networkErr?.statusText !== undefined &&
    networkErr?.response !== undefined

```

## Checklist

1. Closes 

2. How was this tested:

3. Any docs updates needed?

### CODE REVIEW

**Review by stevekinney — APPROVED** [review]
What was the logic for `isNetworkError` and is it being used anywhere else?

We use it on a few __error layouts to show statusCode/statusText. I think we could probably keep it if we remove the response check:

export function isNetworkError(
  error: unknown | NetworkError,
): error is NetworkError {
  const networkErr = error as NetworkError;
  return (
    networkErr?.statusCode !== undefined &&
    networkErr?.statusText !== undefined &&
    networkErr?.response !== undefined
  );
}

**Comment by Alex-Tideman** [comment]
We use it on a few __error layouts to show statusCode/statusText. I think we could probably keep it if we remove the response check:

```
export function isNetworkError(
  error: unknown | NetworkError,
): error is NetworkError {
  const networkErr = error as NetworkError;
  return (
    networkErr?.statusCode !== undefined &&
    networkErr?.statusText !== undefined &&
    networkErr?.response !== undefined
  );
}

```

**Comment by Alex-Tideman** [comment]
@GiantRobots You remember if there was a specific reason for that response check?

**Comment by feedmeapples** [comment]
> @GiantRobots You remember if there was a specific reason for that response check?

i think it partially comes from the APIs returning always 403 instead of 401?

according to another thread this is what the APIs should do 
image

**Review by GiantRobots — APPROVED** [review]

**Comment by GiantRobots** [comment]
The response check in there was because that's how most errors looked when I was adding error boundaries and the like into everything. Other errors need to be surfaced in different ways 404's show on the screen, 500's screen etc some are toast's.

**Pull request merged**
